# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

backend: Auto

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"


  # Signature
  - trigger: ":sig"
    replace: "Please don’t hesitate to contact the IT service desk if you have any further issues, questions or concerns.\n
\n
Phone : 1800 070 257\n
Email : Servicedesk@chcs.com.au\n
You can also log into Service now and use a self-service function to log a ticket at:\n
https://catholichealthcare.service-now.com\n
\n
Kind regards,\n
Steven Glasziou | Service Desk Analyst | Information Services\n
Catholic Healthcare Limited\n
Suite 1, Level 5\n
15 Talavera Road, Macquarie Park NSW  2113\n
PO Box 914, Macquarie Park NSW 1670\n
www.catholichealthcare.com.au\n"


# Signature Possibly Resolved
  - trigger: ":sin"
    replace: "If these suggestions don't resolve the issue, please ring the Service Desk as soon as possible and we will troubleshoot in order to resolve your issue.\n
    \n
Phone : 1800 070 257\n
Email : Servicedesk@chcs.com.au\n
You can also log into Service now and use a self-service function to log a ticket at:\n
https://catholichealthcare.service-now.com\n
  
Kind regards,\n
Steven Glasziou | Service Desk Analyst | Information Services\n
Catholic Healthcare Limited\n
Suite 1, Level 5\n
15 Talavera Road, Macquarie Park NSW  2113\n
PO Box 914, Macquarie Park NSW 1670\n
www.catholichealthcare.com.au\n"


  # Call Questions
  - trigger: ":cs"
    replace: "# Initial Contact Template\n
\n
**Hello, this is the IT Service desk, $YOU speaking. How can I help?**\n
\n
## Questions for the User\n
\n
1. What is your username?\n
>\n
2. What are you trying to do?\n
>\n
3. What is a brief description of the issue?\n
>\n
4. Where are you?\n
>\n
5. What type of device is it?\n
>\n
6. What is the Asset Number of the device? / Which server are you on? / What is the extension number?\n
>\n
7. When did you first notice the issue?\n
>\n
8. When was the last time it worked?\n
>\n
9. Has anything changed since this issue started?\n
>\n
10. Have you had this problem before? If so, when?\n
>\n
11. What have you done already to try and fix the problem?\n
>\n
12. Is anyone else you know of experiencing this issue?\n
>\n
13. What impact does this issue have on you, or your team, or department?\n
>\n
14. What is the best way to contact you?\n
>\n
\n
\n
## Troubleshooting\n
\n
-\n
\n
\n 
## Service Desk Checklist\n
\n
1. What have you restarted?\n
>\n
2. Have you clear any cache / profile?\n
>\n
3. Have you got a copy of any relevant logs / error messages?\n
>\n
4. Is the problem always reproducible? If so, what are the exact steps to reproduce?\n
>\n
5. What is the root cause? / Is there already a problem ticket? / Is there an existing ticket?\n
>\n
\n
**Is there anything else I can do for you today?**"

# Get Info
  - trigger: ":info"
    replace: "To resolve your issue, we need more information. Please either reply with answers to the questions below or call us on 1800 070 257.\n
\n
1. What are you trying to do?\n
2. What is the issue? Please include as much detail as possible.\n
3. Are you getting an error message? If so, what is the exact error message?\n
4. When did the problem begin? Did anything change around that time?\n
5. Do you know of anyone else who is experiencing this issue?\n
6. What impact does this issue have on you, or your team, or department?\n
\n
If possible, please attach a screenshot or photo of the issue. If you are unsure how to do so, please refer to the guides below:\n
For computers https://support.microsoft.com/en-us/help/4027213/windows-10-open-snipping-tool-and-take-a-screenshot\n
or\n
For phones https://www.samsung.com/us/support/answer/ANS00038721/\n
\n
In order to ensure that all issues are attended to promptly, this ticket will be closed if we do not receive a response within 10 days."

# Add Printer
  - trigger: ":printer"
    replace: "In order to add a printer to you session:\n
1. 0pen any Microsoft program (eg Word or Outlook)\n
2. Go to the file tab and open the print menu\n
3. Open the printer drop down and select add printer\n
4. Press ok to the error message that pops up\n
5. Search for the printer by its name and then add the printer\n"


# Spam
  - trigger: ":spam"
    replace: "This does appear to be a spam message. Thank you for forwarding it to the IT Service Desk and being vigilant to cybersecuirty risks.  Please delete the message without opening it or any links from it.\n"


# Adobe
  - trigger: ":adobe"
    replace: "In order to resolve this issue with Adobe:\n
1. Set the default program for PDFs to Acrobat Reader\n
  a. Right click on a PDF\n
  b. Select 'open with'
  c. Select 'choose another app'\n
  d. Select 'Adobe Acrobat Reader'\n
  e. Tick the always open with option\n
2. Use Chrome to open all PDFs from websites. Internet Explorer will no longer open PDFs.\n"


# Bookmark
  - trigger: ":bookmark"
    replace: "Unfortunately, at this point there are no plans to restore the previous Chrome bookmarks. I have been advised that any bookmarks that you create from now on will persist through logout."


# Request
  - trigger: ":request"
    replace: "In order to place a request you have to use the IT Service Catalog, which can be found at:\n
https://catholichealthcare.service-now.com/nav_to.do?uri=%2Fcom.glideapp.servicecatalog_category_view.do%3Fv%3D1%26sysparm_parent%3Db68c3096db2c660081d1f389bf96198e%26sysparm_catalog%3De0d08b13c3330100c8b837659bba8fb4%26sysparm_catalog_view%3Dcatalog_default%26sysparm_view%3Dcatalog_default\n
\n
Items cannot be order through an Incident, so I will be closing this Incident."


# Mactel Data Alert
  - trigger: :data
    replace: "You can use 100% of your data 4 months in a row before your service will be locked. In general, we don't worry until the service has been locked. If you do loose access the internet, please give us a call on 1800 070 257."


# Shortcut
  - trigger: ":shortcut"
    replace: "You can create a shortcut on your desktop:\n
1. Right click or press and hold on your desktop, click/tap on New, and click/tap on Shortcut.\n
2. Copy (Ctrl+C) and Paste (Ctrl+V) the URL address of the website (ex: https://connect.chcs.com.au) you want to create a shortcut to into the location field, and click/tap on Next.\n
3. Type a name you want for this website shortcut\n
4. Click/tap on Finish."


# General Help
  - trigger: ":help"
    replace: "Please find below a help article which I believe will help resolve your issue:"


# Logout to Solve
  - trigger: ":log"
    replace: "Please try signing out and then signing back in. Do not use the disconnect button in Sapphire, please use the sign out button which you can get by clicking on the profile icon (two icons above the power icon in the Start menu)."


# Restore an item
  - trigger: ":backup"
    replace: "In order to restore an item:\n
1. Right click the folder where the item was previously.\n
2. Select Properties\n
3. Select Previous Versions\n
4. Select the folder that is labeled with a time close to when you last saw the item\n
5. Drag the item from the historic folder to the live/current folder"


# Personal Device
  - trigger: ":personal"
    replace: "Unfortunately, the Catholic Healthcare IT Service Desk cannot guarantee the function of personal devices. We can only provide limited troubleshooting a suggestions for these devices.\n
In this case we have exhausted the troubleshooting we can do for this issue and will therefore be closing the ticket.\n
\n
If you believe this is in error or if it is preventing you completing your work, please contact your manager"


# Personal Device
  - trigger: ":oldemail"
    replace: "This is due to a performance enhancing change made in Sapphire. We now only load recent emails rather than all of them. This significantly speeds the system up for everyone.\n
\n
In order to access older email you can either go to https://outlook.office365.com or search for them in your Desktop Outlook, which will retrieve them from the server. For instance this:\n
received>1/1/2010\n
will retrieve all mail in that folder sent after 2010. For more please see:\n
https://support.office.com/en-us/article/Learn-to-narrow-your-search-criteria-for-better-searches-in-Outlook-D824D1E9-A255-4C8A-8553-276FB895A8DA"


# Closed as a duplicate
  - trigger: ":dup"
    replace: "I am closing this ticket as a duplicate of the original ticket\n
    \n
    The original ticket has been updated with your new message and I am chasing up the status of the ticket. I have to close this ticket in order to ensure that we can keep the best possible idea of which issues are still outstanding."


# Pay Week
  - trigger: ":payweek"
    replace: "During pay week, Monday to Wednesday SALi (HRESS) is unavailable to submit, approve or change leave.\n
\n
Once the payrun is completed, SALi will be available again to submit, approve or cancel leave."
    
## Temp
# Phone Upgrade
  - trigger: ":intune"
    replace: "Unfortunately, we are unable to assist with this issue.\n
\n
Please speak to your direct manager/admin staff and they will be able to help you."

## Quality of Life
# Catholic Healthcare
  - trigger: ":chl"
    replace: "Catholic Healthcare"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  # Ecase
  - trigger: "@ch"
    replace: "@chcs.com.au"
